#!/bin/bash
clear
if [[ $(diskutil list external) ]]; then #check empty output
    diskutil list external
    read -p "Inserire IDENTIFIER: " IDENTIFIER
    read -p "Inserire NOME: " NOME
    device="/dev/$IDENTIFIER"
    directory="/Volumes/$NOME"
    sudo diskutil unmountDisk $device
    sudo mkdir $directory
    sudo /usr/local/sbin/mount_ntfs $device $directory
    open -a finder $directory
else 
    echo Nessun device esterno collegato
fi  
